NDefines.NAI.PRODUCTION_EQUIPMENT_SURPLUS_FACTOR = 0.01
NDefines.NAI.WANTED_UNITS_INDUSTRY_FACTOR = 1
NDefines.NAI.WANTED_UNITS_THREAT_BASE = 1
NDefines.NAI.WANTED_UNITS_THREAT_MAX = 1
NDefines.NAI.WANTED_UNITS_MANPOWER_DIVISOR = 100