NDefines.NProject.FACILITY_SUPPLY_WARNING_RED_RATIO = 0.01 --When lacking supply for a facility it will be a yellow icon shown until the supply is less than this value, where it will turn red.
NDefines.NProject.DEFAULT_COMPLEXITY = 100 --	Default special project prototype phase to only require one iteration.
NDefines.NProject.DEFAULT_EMPTY_REWARD_WEIGHT = 1.0 --The weight for no reward being given after a prototype iteration.
NDefines.NProject.DEFAULT_STOP_PROJECT_DAYS = 1 --	The amount of days it takes for a cancelled project to be stopped.
NDefines.NProject.DAYS_TO_REMOVE_SCIENTIST = 1 --	Amount of days needed for a scientist to be unassigned.
NDefines.NProject.DISMANTLE_FACILITY_DAYS = 1 -- Amount of days needed to dismantle a facility.
NDefines.NProject.PROTOTYPE_PHASE_MAX_PROGRESS = 1 --the number of progress points needed to finish the prototype phase and complete the project
NDefines.NProject.MINIMUM_PROJECT_SPEED_FACTOR_FROM_SUPPLY = 0.1 --	Minimum special project research speed based on supply
NDefines.NProject.NEEDED_SUPPLY_FOR_FULL_SPEED_PROJECT = 1.0
NDefines.NProject.MINIMUM_PROJECT_SPEED_FACTOR_FROM_RESOURCE_SHORTAGE = 1
NDefines.NProject.ITERATION_REWARD_DEFAULT_WEIGHT = 1
NDefines.NProject.DEFAULT_PROJECT_COMPLETION_SCIENTIST_EXPERIENCE_GAIN = 1
NDefines.NProject.SCIENTIST_INJURED_FACTOR = 1
NDefines.NProject.RECRUIT_SCIENTIST_ONE_TRAIT_CHANCE = 1
NDefines.NProject.SCIENTIST_BASIC_RESEARCH_DAILY_XP_GAIN = 1
NDefines.NProject.RECRUIT_SCIENTIST_COST = {1, 2, 3, 4, 5}
NDefines.NProject.SCIENTIST_SKILL_LEVEL_THRESHOLDS = {10, 20}
NDefines.NProject.SCIENTIST_SKILL_LEVEL_SPEED_MODIFIER = {1, 2, 3}
NDefines.NProject.PROJECT_LOSS_FACTOR_ON_CAPTURE = 0.01
NDefines.NProject.PROJECT_CAPTURE_GAIN_RATIO = 0.01
NDefines.NProject.PROJECT_CAPTURE_BREAKTHROUGH_PROGRESS = 0.01
NDefines.NProject.PROJECT_CAPTURE_DIMINISHING_RETURN = 0.01
NDefines.NProject.BASIC_RESEARCH_TECHNOLOGY_BONUS_FACTOR = 0.01
NDefines.NProject.BASIC_RESEARCH_TECHNOLOGY_BONUS_DIMINISHING_RETURN_FACTOR = 0.01
NDefines.NProject.BREAKTHROUGH_DAILY_TECHNOLOGY_GAIN = 100
NDefines.NProject.BREAKTHROUGH_DAILY_SCIENTIST_SKILL_GAIN = 100
NDefines.NProject.BREAKTHROUGH_DAILY_ROCKET_SITE_GAIN = 1
NDefines.NProject.BREAKTHROUGH_DAILY_NUCLEAR_REACTOR_GAIN = 1
NDefines.NProject.BREAKTHROUGH_GAIN_ANIMATION_SPEED_MAX = 100
